name: Create Release and Upload VSIX

on:
  push:
    tags:
      - "*"

jobs:
  build-release:
    name: Build and Release VSIX
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Package Extension
        run: npm run package

      - name: Determine VSIX filename
        id: get_vsix_name
        # vsce package outputs the filename, but it's simpler to reconstruct it
        # Need jq to parse package.json
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          EXT_NAME=$(jq -r .name package.json)
          EXT_VERSION=$(jq -r .version package.json)
          echo "vsix_path=${EXT_NAME}-${EXT_VERSION}.vsix" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2 # Use v2 for latest features
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release notes for ${{ github.ref_name }}
            _Auto-generated by GitHub Actions._
          draft: false
          prerelease: false
          files: |
            ${{ steps.get_vsix_name.outputs.vsix_path }}
